.php70: &php70
  image: thedxw/php-testing:7.0

.php71: &php71
  image: thedxw/php-testing:7.1

.peridot-api: &peridot-api
  before_script:
    # Set timezone
    - echo 'date.timezone = Pacific/Auckland' >> /usr/local/etc/php/conf.d/tz.ini
    - cd 'wp-content/plugins/dxw-sec-api'
    - composer install
  script:
    - vendor/bin/peridot specs

.peridot-theme: &peridot-theme
  before_script:
    - cd 'wp-content/themes/dxw-security-2017'
    - composer install
  script:
    - vendor/bin/peridot spec

.api_style: &api_style
  before_script:
    - cd 'wp-content/plugins/dxw-sec-api'
    - composer install
  script:
    - vendor/bin/phpcs lib specs --standard=PSR2

.theme_style: &theme_style
  before_script:
    - cd 'wp-content/themes/dxw-security-2017'
    - composer install
  script:
    - vendor/bin/php-cs-fixer fix --dry-run -v --diff

php_70_tests_api:
  <<: *php70
  <<: *peridot-api

php_70_tests_theme:
  <<: *php70
  <<: *peridot-theme

php_71_tests_api:
  <<: *php71
  <<: *peridot-api

php_71_tests_theme:
  <<: *php71
  <<: *peridot-theme

api_style:
  <<: *php71
  <<: *api_style

theme_style:
  <<: *php71
  <<: *theme_style

# validate json
include:
  - project: 'dxw/gitlab-ci-configs'
    file: 'valid-json.gitlab-ci.yml'
