.php70: &php70
  image: thedxw/php-testing:7.0

.php71: &php71
  image: thedxw/php-testing:7.1

.peridot: &peridot
  before_script:
    # Set timezone
    - echo 'date.timezone = Pacific/Auckland' >> /usr/local/etc/php/conf.d/tz.ini
    - cd 'wp-content/plugins/dxw-sec-api'
    - composer install
  script:
    - vendor/bin/peridot specs

.api_style: &api_style
  before_script:
    - cd 'wp-content/plugins/dxw-sec-api'
    - composer install
  script:
    - vendor/bin/phpcs lib specs --standard=PSR2

.theme_style: &theme_style
  before_script:
    - cd 'wp-content/themes/dxw-advisories-2017'
    - composer install
  script:
    - vendor/bin/phpcs lib/helpers.php --standard=PSR2 --warning-severity=false

php_70_tests:
  <<: *php70
  <<: *peridot

php_71_tests:
  <<: *php71
  <<: *peridot

api_style:
  <<: *php71
  <<: *api_style

theme_style:
  <<: *php71
  <<: *theme_style
